apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: cloud-vip
  namespace: kube-system
spec:
  containers:
    - args:
        - "--cafile=/etc/kubernetes/pki/etcd/ca.crt"
        - "--clientcertfile=/etc/kubernetes/pki/etcd/peer.crt"
        - "--clientkeyfile=/etc/kubernetes/pki/etcd/peer.key"
        - "--address=172.16.222.100/24"
        - "--nicslave=bond4"
        - "--nicmaster=br0"
        - "--leaseduration=5"
        - "--leasename=cloudvip"
        - "--endpoints"
        - "https://127.0.0.1:2379"
      image: 843592242/election-vip:v0.2
      imagePullPolicy: IfNotPresent
      name: cloud-vip
      resources: {}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
  hostNetwork: true
  volumes:
    - hostPath:
        path: /etc/kubernetes/pki/etcd
      name: etcd-certs
status: {}