apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: mysql-vip
  namespace: kube-system
spec:
  containers:
    - args:
        - "--election=mysql-vip"
        - "--namespace=kube-system"
        - "--locktype=configmaps"
        - "--port=4040"
      env:
        - name: address
          value: 192.168.19.252/32
        - name: IP
          value: 10.240.19.130
      image: harbor.com/test/election-vip:0.6
      imagePullPolicy: IfNotPresent
      name: mysql-vip
      resources: {}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: sa
  hostNetwork: true
  volumes:
    - hostPath:
        path: /opt/mysql-vip
      name: sa
status: {}