apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-vip
  namespace: kube-system
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-vip
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: mysql-vip
roleRef:
  kind: Role
  name: mysql-vip
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-vip
  namespace: kube-system